<!--------------------------- loding ---------------------------------------->

<div data-role="loader" class="loading-mask" id="mcs-custom-loader" style="display:none;z-index:999;">
    <div class="loader">
        <img src="<?php /* @noEscape */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
             alt="<?php /* @noEscape */ echo __('Loading...') ?>">
    </div>
</div>
<!---------------------------  loding ---------------------------------------->
