<div class="home-about container">

  <div class="row">
    <div class="col-sm-6">
      <div class="about-image">
        <div class="home-about-blue-area"></div>
        <div class="home-about-light-blue-area"></div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="about-text">
        <h1>ECOMERCHANT</h1>
        <h2>With over 2,000 product lines including top brands and proven performance products plus UK-wide delivery direct from stock, we can always help you find the right tool for the job.</h2>
        <p>Vestibulum vestibulum parturient consectetur dolor molestie facilisis suspendisse lobortis sociosqu adipiscing curae quis vestibulum a molestie adipiscing scelerisque egestas dignissim himenaeos vivamus conubia sit elit nec sit.Dolor vulputate ad praesent parturient neque donec feugiat a vulputate conubia a cursus fames.</p>
        <a href="#" class="round-button">MORE ABOUT US</a>
      </div>
    </div>
  </div>

</div>