<?php
/**
 * @var $this Scommerce_GoogleTagManagerPro_Block_Gtm
 */
?>
<?php
$helper = $this->getHelper();
if ($helper->isEnhancedEcommerceEnabled()): 
	$addedProduct = $this->getAddToBasketData();
	$removedProduct = $this->getRemoveFromBasketData();
	if ($addedProduct || $removedProduct):?>
    <script>
        //<![CDATA[
        function manipulationOfCart(product, type, list) {
            //product = eval("(" + product + ")");

            if (list == 'undefined'){
                list='Category - '+ product.category
            }
            
			if (type == 'add'){
                dataLayer.push({
                    'event': 'addToCart',
                    'ecommerce': {
                        'currencyCode': product.currency,
                        'add': {                                // 'add' actionFieldObject measures.
                            'products': [{                        //  adding a product to a shopping cart.
                                'name': product.name,
                                'id': product.id,
                                'price': product.price,
                                'brand': product.brand,
                                'category': product.category,
                                'quantity': product.qty,
                                'list': list
                            }]
                        }
                    }
                });
            }
            else if (type == 'remove') {
                dataLayer.push({
                    'event': 'removeFromCart',
                    'ecommerce': {
                        'currencyCode': product.currency,
                        'remove': {                                // 'remove' actionFieldObject measures.
                            'products': [{                        //  adding a product to a shopping cart.
                                'name': product.name,
                                'id': product.id,
                                'price': product.price,
                                'brand': product.brand,
                                'category': product.category,
                                'quantity': product.qty,
                                'list': list
                            }]
                        }
                    }
                });
            }
        }
		<?php if ($addedProduct):?>    
        require(['jquery', 'mage/cookies'], function($){
			$(window).load(function() {
                var productToBasket = <?php echo $addedProduct?>;
                var productlist = $.mage.cookies.get("productlist");

                if (productToBasket != undefined) {
                    manipulationOfCart(productToBasket, 'add', productlist);
                    $.mage.cookies.clear("productlist");
                }
				<?php $this->unsAddToBasketData();?>
            });
        });
		<?php endif;?>
		
		<?php if ($removedProduct):?>    
        require(['jquery', 'mage/cookies'], function($){
			$(window).load(function() {
                var productOutBasket = <?php echo $removedProduct?>;
                
				if (productOutBasket != undefined) {
                    manipulationOfCart(productOutBasket, 'remove', '');
                }
				<?php $this->unsRemoveFromBasketData();?>
            });
        });
		<?php endif;?>		
        //]]>
    </script>
	<?php endif;?>
<?php endif;?>

<!-- Scommerce Mage Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
		new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
		j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
	})(window,document,'script','dataLayer','<?php echo $helper->getAccountId() ?>');</script>
<!-- Scommerce Mage End Google Tag Manager -->