<?php
/**
 *
 * @var $this Scommerce\GoogleTagManagerPro\Block\ListProduct
 */
?>

<?php
$helper = $this->getHelper();
if (!$helper->isEnhancedEcommerceEnabled() || $helper->isCategoryAjaxEnabled()) return;

$_SIOSEnabled = $helper->isSIOSEnabled();
$_PICText = $helper->getPICText();

$_productCollection = $this->getProductCollection();

$_category = $this->getLayer()->getCurrentCategory();
if ($_category->getDisplayMode() == $this->getCMDisplayMode()) return;

$_categoryName = '';
$_impressionList = '';

if ($_category){
	$_categoryName = $_category->getName();
}

//Zend_Debug::dump($_categoryName);

$_mode = $this->getMode();
$_productUrls = array();
$_products = array();

if ($_mode == 'category') {
	$_impressionList = 'Category' .' - '. $_categoryName;
}
elseif ($_mode == 'search') {
	$_impressionList = 'Search Results';
}

$_loop = 1;

foreach ($_productCollection as $_product){
	$_productUrls[] = $_product->getProductUrl();

	$_products[] = array(
		'id' => $this->escapeJsQuote($_product->getSku()),
		'name'  => $this->escapeJsQuote($_product->getName()),
		'category' => ($_mode=='search'? $helper->getProductCategoryName($_product) : $this->escapeJsQuote($_categoryName)),
		'brand' => $this->escapeJsQuote($helper->getBrand($_product)),
		'list'  => $_impressionList,
        'price' => $helper->productPrice($_product),
		'position' => $_loop
	);

	$_loop++;
}

$_JsProducts = json_encode($_products);
$_JsProductUrls = json_encode($_productUrls);
?>

<script type='text/javascript'>
	//<![CDATA[
	<?php if (($_SIOSEnabled) && strlen($_PICText)):
		$productItemClass = $_PICText;
		if (strlen($productItemClass)==0) $productItemClass = "div.products ol.product-items li.product-item";?>
		var jsProducts    = <?php echo $_JsProducts ?>;
		var jsProductUrls = <?php echo $_JsProductUrls ?>;
		var jsClickLabel  = '<?php echo $_impressionList?>';
		var intCtr = 0;
		var lastCtr = 0;
			
		require(['jquery','jqueryviewport'], function($) {
			$(document).ready(function () {
				$('<?php echo $productItemClass?>').inviewport({
				  threshold: 10
				});
			});
			$(window).bind("scroll load", function() {
				var JsonObj = {};	
				JsonObj.impressions = [];
				//console.log($('.in-view').size());
				$('.in-view').each(function(){
					var id = this;
					var classNames = $(this).attr('class');
					$.each(jsProducts, function (index, product) {
						var pos = classNames.indexOf('impressionSent');
						if (pos < 0 && index>=intCtr){
							$(id).addClass('impressionSent');
							var impression = {
								'id': product.id,
								'name': product.name,
								'price': product.price,
								'category': product.category,
								'brand': product.brand,
								'list': product.list,
								'position': product.position
							}
							JsonObj.impressions.push(impression);							
							intCtr++;
							//console.log(intCtr);
							return false;
						}
					});
				});
				if (intCtr>0 && lastCtr<intCtr){ 
					window.dataLayer = window.dataLayer || [];
					dataLayer.push({
						'event': 'listingScroll',
						'ecommerce': JsonObj
					});
					lastCtr=intCtr;
				}
			});			
		});		
	<?php else:?>
		window.dataLayer = window.dataLayer || [];
		dataLayer.push({
			'ecommerce': {
				'currencyCode': '<?php echo $helper->getCurrencyCode();?>',                       // Local currency is optional.
				'impressions': [
					<?php foreach ($_products as $_product):?>
					{
						'name': '<?php echo $_product['name']?>',
						'id': '<?php echo $_product['id']?>',
						'price': '<?php echo $_product['price']?>',
						'brand': '<?php echo $_product['brand']?>',
						'category': '<?php echo $_product['category']?>',
						'list': '<?php echo $_product['list']?>',
						'position': '<?php echo $_product['position']?>'
						<?php if ($_product['position']==count($_products)):?>
					}]
				<?php else:?>
			},
			<?php endif;?>
			<?php endforeach;?>
		   }
		});
	<?php endif;?>
    //]]>
</script>

<script type='text/javascript'>
	//<![CDATA[
	require(['jquery', 'mage/cookies'], function($) {
		$(window).load(function () {
            <?php if (!($_SIOSEnabled)):?>
			var jsProducts = <?php echo $_JsProducts ?>;
            var jsProductUrls = <?php echo $_JsProductUrls ?>;
			<?php endif;?>
			jQuery('a').on('click', function(e){
				var product;
				var href = jQuery(this).attr('href');
				var index = jsProductUrls.indexOf(href);

				if (index != -1){
					//event.preventDefault();
                    product = jsProducts[index];
                    //console.log(product.name + ' - clicked');
					$.mage.cookies.set('productlist', product.list);
					
					dataLayer.push({
                        'event': 'productClick',
                        'ecommerce': {
                            'click': {
                                'actionField': {'list': product.list},      // Optional list property.
                                'products': [{
                                    'name': product.name,                      // Name or ID is required.
                                    'id': product.id,
                                    'price': product.price,
                                    'brand': product.brand,
                                    'category': product.category,
                                    'position': product.position
                                }]
                            }
                        },
                        'eventCallback': function() {
                            if (!(e.ctrlKey || e.which==2)){
                                document.location = href;
                            }
                        }
                    });
				}
			});
		});
	});
	//]]>
</script>