<?php
/**
 * @category    FishPig
 * @package     FishPig_WordPress
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php /*?><?php if ($text = $this->getIntroText()): ?>
	<p class="post-list-description"><?php echo $text ?></p>
<?php endif; ?><?php */?>
<?php if ($postList = trim($this->getPostListHtml())): ?>
	<?php echo $postList ?>
<?php else: ?>
	<p class="note-msg"><?php echo __('There are no posts matching your selection.') ?>
<?php endif; ?>