<?php
/**
 * Quote grid.
 *
 * @category  Webkul
 * @package   Webkul_Quotesystem
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

?>
<?php
    $helper = $block->getHelper();
    $currencySymbol = $helper->getCurrentCurrencySymbol();
    $quotedProductsData = $helper->getQuoteDataInRegistry();
    $showCart = (int)$helper->getConfigAddToCart();
    $showPrice = (int)$helper->getConfigShowPrice();
?>
<div style="display:none" id="wk-qs-ask-data">
    <form id="quotesystem_quote_add_cat" method="post" action="<?= $block->escapeUrl($block->getUrl(
        'quotesystem/buyerquote/savequote',
        ['_secure' => $block->getIsSecure()]
    ))?>">
        <input type="hidden" name="product_name" value="" />
        <input type="hidden" name="product" value=""/>
        <input type="hidden" name="current_url" value="" />
        <div class="fieldset" >
            <div>
                <label for="quote_qty"><?= /* @noEscape */ __("Quantity"); ?> :</label>
                <input type="text" id="quote_qty" name="quote_qty" class="quote_qty" data-validate="{required:true,'validate-greater-than-zero':true, 'validate-number':true}"/>
                <span class="wk-qs-min-qty"></span>
            </div>
            <div>
                <label for="quote_price"><?= /* @noEscape */ __("Price per Item")."(".$currencySymbol.")"; ?> :</label>
                <input type="text" id="quote_price" name="quote_price" class="quote_price" data-validate="{required:true,'validate-greater-than-zero':true, 'validate-number':true}"/>
            </div>
            <div>
                <label for="quote_description"><?= /* @noEscape */ __("Description"); ?> :</label>
                <textarea id="quote_description" name="quote_description" class="quote_description" data-validate="{required:true}"></textarea>
            </div>
            <div class="wk-file-field-container">
                <label class="label wk-file-label wk-quote-primary-btn">
                    <?= /* @noEscape */ __('Add Attachment(s)') ?>
                    <input type="file" name="files" class="wk-file-field" id="wk-file-field" data-url="<?= $block->escapeUrl($block->getUrl('quotesystem/buyerquote/fileUpload', ['_secure' => $block->getRequest()->isSecure()])) ?>" multiple="multiple"/>
                </label>
            </div>
        </div>
    </form>
</div>
<a class="proceed-to-checkout button primary" style="display:none">
    <?= /* @noEscape */ __('Login') ?>
</a>
<script id="wk-file-field-template" type="text/x-magento-template">
    <div class="wk-uploaded-file">
        <span class="wk-uploaded-file-style wk-quote-primary-btn"><%- data.extension %></span>
        <span class="wk-uploaded-file-name"><%- data.name %></span>
        <input type="hidden" name="attachments[]" value="<%- data.file %>" class="wk-uploaded-file-value"/>
        <span class="wk-uploaded-file-del"></span>
    </div>
</script>
<script id="wk-file-field-uploader-template" type="text/x-magento-template">
    <div id="<%- data.id %>" class="wk-uploaded-file-row">
        <img src="<?= $block->escapeUrl($block->getViewFileUrl('Webkul_Quotesystem/images/ajax-loader-big.gif'))?>"/>
    </div>
</script>

<?php
    
    $formData = [
        'quoteProductData'  =>  $quotedProductsData,
        'productitems'      => '.product-items li',
        'loginurl'          => $block->getUrl('customer/account/login'),
        'popoverbackgroundhtml' =>  '#wk-qs-ask-data',
        'popoverClass'          =>  '.popover',
        'popOverclose'          =>  '.popover_close',
        'categorySubmitButton'  =>  '.submit_button',
        'maxWidth'              =>  \Magento\Framework\File\Uploader::MAX_IMAGE_WIDTH,
        'maxHeight'             =>  \Magento\Framework\File\Uploader::MAX_IMAGE_HEIGHT,
        'fileDeleteUrl'            =>  $block->getUrl(
            'quotesystem/buyerquote/fileDelete',
            ['_secure' => $block->getRequest()->isSecure()]
        ),
        'showCart'          => $showCart,
        'showPrice'         => $showPrice
    ];
    $serializedFormData = $block->getJsonHelper()->jsonEncode($formData);
    ?>
<script type="text/x-magento-init">
    {
        "*": {
            "WkQuotesystem": <?= /* @noEscape */$serializedFormData; ?>
        }
    }
</script>
