<div class="home-categories container">

  <div class="row">
    <div class="col-md-6">
      <div class="cat-box new-product">
        <h2>NEW PRODUCTS</h2>
        <a class="round-button" href="/new-product.html">SHOP NOW</a>
      </div>
    </div>
    <div class="col-md-6">
        <div class="cat-box windows-doors">
          <h2>WINDOWS &amp; DOORS</h2>
          <a class="round-button" href="/walls/windows-doors.html">SHOP NOW</a>
        </div>
      <div class="row">
        <div class="col-6">
          <div class="cat-box airtightness">
            <h2>AIRTIGHTNESS</h2>
            <a class="round-button" href="/airtightness.html">SHOP NOW</a>
          </div>
        </div>
        <div class="col-6">
          <div class="cat-box paints">
            <h2>PAINTS</h2>
            <a class="round-button" href="/walls/windows-doors.html">SHOP NOW</a>
          </div>
        </div>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="cat-box lime-products">
        <h2>LIME PRODUCTS</h2>
        <a class="round-button" href="/walls/windows-doors.html">SHOP NOW</a>
      </div>
    </div>
    <div class="col-md-6">
      <div class="cat-box drainage-water">
        <h2>DRAINAGE &amp; WATER</h2>
        <a class="round-button" href="/walls/windows-doors.html">SHOP NOW</a>
      </div>
    </div>
  </div>

</div>