<script>
function resetColumns(cols){
    jQuery('.products-row > div').removeClassRegex(/col-sm-/);
    switch (cols) {
        case 3:
            jQuery('.products-row > div').addClass('col-sm-4');
            break;
        case 4:
            jQuery('.products-row > div').addClass('col-sm-3');
            break;
        case 5:
            jQuery('.products-row > div').addClass('col-sm-custom');
            break;
        default:
            break;
    }
}
require([
        'jquery'
    ], function ($) {

        jQuery.fn.removeClassRegex = function(regex) {
            return $(this).removeClass(function(index, classes) {
                return classes.split(/\s+/).filter(function(c) {
                return regex.test(c);
                }).join(' ');
            });
        };
});
</script>

<div class="toolbar-col-view">
    <a class="col-view-btn cvb1" href="javascript:void(0);" onclick="resetColumns(3);"></a>
    <a class="col-view-btn cvb3" href="javascript:void(0);" onclick="resetColumns(4);"></a>
    <a class="col-view-btn cvb2" href="javascript:void(0);" onclick="resetColumns(5);"></a>
</div>
