<?php
/**
 * Quote product .phtml
 *
 * @category  Webkul
 * @package   Webkul_Quotesystem
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

?>
<?php
// use to allow customer to quote on a product
$product = $block->getProduct();
$stockstatus = $block->isInStock();
$status = $product->getQuoteStatus();
$qty = $block->getProductQty();
$quoteHelper = $block->getHelper();
$currencySymbol = $quoteHelper->getCurrentCurrencySymbol();
$showCart = (int)$quoteHelper->getConfigAddToCart();
$showPrice = (int)$quoteHelper->getConfigShowPrice();

if (($status == 1) && $stockstatus == 1) {
    $minqty = 0;
    if ($product->getMinQuoteQty()):
        $minqty = $product->getMinQuoteQty();
    else:
        $minqty = $quoteHelper->getConfigMinQty();
    endif; ?>
    <button
        type="button"
        title="<?= /* @noEscape */ __("Quote This Product");?>"
        class="wk_qs_quote_button button btn-cart action primary">
        <span><span><?= /* @noEscape */ __("Quote This Product"); ?></span></span>
    </button>
    <?php
    $finalPrice = 0;
    if ($product->getSpecialPrice() != "") {
        $finalPrice = $product->getSpecialPrice();
    } else {
        $finalPrice = $product->getPrice();
    } ?>
    <div class="ask-que popover_background">
        <div id="wk-qs-ask-data">
            <!-- <div class="modals-wrapper"> -->
                <div tabindex="0"
                    data-type="popup"
                    data-role="modal"
                    class="modal-popup modal-slide _inner-scroll wk-mp-model-popup">
                    <div tabindex="0" data-role="focusable-start"></div>
                    <div data-role="focusable-scope" class="modal-inner-wrap wk-qs-inner-wrap">
                        <header class="modal-header">
                            <h4 class="modal-title"><?= /* @noEscape */ __('Enter Quote Details') ?></h4>
                            <!-- <span  class="wk-close" >x</span> -->
                            <button type="button"
                                data-role="closeBtn"
                                class="popover_close action-close wk-close"
                            >
                                <span>Close</span>
                            </button>
                            <span  class="wk-clear" ></span>
                        </header>
                        <div class="modal-body form-list field required">
                        <fieldset class="fieldset info wk-mp-fieldset">
                            <input type="hidden"
                                name="original_price"
                                value="<?= $block->escapeHtml($finalPrice); ?>"
                            />
                            <input type="hidden"
                                name="product_name"
                                value="<?= $block->escapeHtml($product->getName()); ?>"
                            />
                            <input type="hidden"
                                name="current_url"
                                value="<?= $block->escapeUrl($block->getCurrentUrl()); ?>"
                            />
                            <input type="hidden"
                                name="product_quantity"
                                value="<?= $block->escapeHtml($qty); ?>"
                            />
                            <div class="field required">
                                <label class="label"><?= /* @noEscape */ __("Quantity"); ?> :</label>
                                <div class="control">
                                    <input type="text"
                                        class="queryquestion wk-contact_input_fields required-entry validate-digits validate-number validate-greater-than-zero validate-digits-range digits-range-<?= $block->escapeHtml($minqty)?>- quote_qty"
                                        id="quote_qty"
                                        name="quote_qty" value=""
                                        data-validate="{required:true,
                                            'validate-number':true,
                                            'validate-digits':true,
                                            'validate-greater-than-zero':true}"
                                    />
                                    <span class="wk-qs-min-qty"><?php if ($minqty) { /* @noEscape */ echo __('minimum quote quantity limit is %1', $minqty); }?></span>
                                </div>
                            </div>
                            <div class="field required">
                                <label class="label">
                                    <?= /* @noEscape */ __("Price per Item")."( ".$currencySymbol." )"; ?> :
                                </label>
                                <div class="control">
                                    <input type="text"
                                        class="queryquestion wk-contact_input_fields required-entry validate-greater-than-zero validate-number quote_price"
                                        id="quote_price"
                                        name="quote_price"
                                        data-validate="{required:true,
                                            'validate-number':true,
                                            'validate-greater-than-zero':true}"
                                    />
                                </div>
                            </div>
                            <div class="field required">
                                <label class="label"><?= /* @noEscape */ __("Description"); ?> :</label>
                                <div class="control">
                                    <textarea
                                        class="queryquestion wk-contact_input_fields required-entry quote_description"
                                        id='quote_description'
                                        name="quote_description"
                                        rows="10"
                                        data-validate="{required:true}"
                                    ></textarea>
                                </div>
                            </div>
                            <div class="wk-file-field-container">
                                <label class="label wk-file-label wk-quote-primary-btn">
                                    <?= /* @noEscape */ __('Add Attachment(s)') ?>
                                    <input type="file" name="files" class="wk-file-field" id="wk-file-field" data-url="<?= $block->escapeUrl($block->getUrl('quotesystem/buyerquote/fileUpload', ['_secure' => $block->getRequest()->isSecure()])) ?>" multiple="multiple"/>
                                </label>
                            </div>
                        </fieldset>
                        </div>
                        <div class="modal-footer wk_footer">
                            <span class="error"></span>
                            <span class="errormail"></span>
                            <input type="reset"
                                value="<?= /* @noEscape */ __('Reset') ?>"
                                id="resetbtn"
                                class="wk-btn wk-btn_default wk_reset"
                            />
                            <input type="button"
                                value="<?= /* @noEscape */ __('Submit') ?>"
                                id="askbtn"
                                class="submit_button wk-btn wk-btn-primary clickask"
                            />
                            <span class="wk-clear"></span>
                        </div>
                    </div>
                    <div tabindex="0" data-role="focusable-end"></div>
                </div>
            <!-- </div> -->
        </div>
    </div>
    <script id="wk-file-field-template" type="text/x-magento-template">
        <div class="wk-uploaded-file">
            <span class="wk-uploaded-file-style wk-quote-primary-btn"><%- data.extension %></span>
            <span class="wk-uploaded-file-name"><%- data.name %></span>
            <input type="hidden" name="attachments[]" value="<%- data.file %>" class="wk-uploaded-file-value"/>
            <span class="wk-uploaded-file-del"></span>
        </div>
    </script>
    <script id="wk-file-field-uploader-template" type="text/x-magento-template">
        <div id="<%- data.id %>" class="wk-uploaded-file-row">
            <img src="<?= /* @noEscape */ $block->getViewFileUrl('Webkul_Quotesystem/images/ajax-loader-big.gif')?>"/>
        </div>
    </script>
<?php } ?>
<a class="proceed-to-checkout button primary" style="display:none">
    <?= /* @noEscape */ __('Login') ?>
</a>
<?php
$formData = [
    'quoteButtonHtml'       =>  '.wk_qs_quote_button',
    'popoverbackgroundhtml' =>  '.popover_background',
    'productAddToCartForm'  =>  '#product_addtocart_form',
    'saveQuoteUrl'          =>  $block->getUrl(
        'quotesystem/buyerquote/savequote',
        ['_secure' => $block->getIsSecure()]
    ),
    'quote_description'     =>  '#quote_description',
    'quote_price'           =>  '#quote_price',
    'quote_qty'             =>  '#quote_qty',
    'redirectUrl'              =>  $block->getUrl('quotesystem/buyerquote/redirectAfterLogin/'),
    'addToCartAction'       =>  '.box-tocart .actions',
    'popOverclose'          =>  '.popover_close',
    'submitButton'          =>  '.submit_button',
    'paypal'                =>  '.paypal',
    'reset'                 =>  '#resetbtn',
    'loginurl'              =>  $block->getUrl('customer/account/'),
    'maxWidth'              =>  \Magento\Framework\File\Uploader::MAX_IMAGE_WIDTH,
    'maxHeight'             =>  \Magento\Framework\File\Uploader::MAX_IMAGE_HEIGHT,
    'fileDeleteUrl'         =>  $block->getUrl(
        'quotesystem/buyerquote/fileDelete',
        ['_secure' => $block->getRequest()->isSecure()]
    ),
    'showCart'          => $showCart,
    'showPrice'         => $showPrice
];
$serializedFormData = $block->getJsonHelper()->jsonEncode($formData);
?>
<script type="text/x-magento-init">
    {
        "*": {
            "WkQuotesystem": <?= /* @noEscape */ $serializedFormData; ?>
        }
    }
	
	
	

</script>
