<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
$helper = $this->helper('Solwin\Cpanel\Helper\Data');
$showgooglemap = $helper->getShowrgooglemap();
?>
<div class="c-add">
    <?php
    $storename = $helper->getContactstorename();
    $storeaddress = $helper->getContactstoreaddress();
    $contactinfo = $helper->getStorecontactno();
    $storeemail = $helper->getStorecontactemail();
    ?>
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact-sidebar')->toHtml();?>
    
</div>
<?php if ($showgooglemap == "1") { ?>
    <?php $embedcode = $helper->getGooglemapembedcode(); ?>
    <div class="contact-map" style="margin:30px 0 20px;float: left;width:100%;">
        <iframe style="border: 0;" src="<?php echo $embedcode; ?>" frameborder="0" width="100%" height="400px"></iframe>
    </div>
<?php } ?>
<style>
.contact-index-index #contact-form {
    float: left;
    width: 70%;
    box-sizing: border-box;
}
</style>
