<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('You may also be interested in the following products(s)');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showWishlist = false;
            $showCompare = false;
            $showCart = true;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('You may also be interested in the following products(s)');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showWishlist = false;
            $showCompare = false;
            $showCart = true;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    case 'other':
        break;
}
?>
<?php
$helper = $this->helper('Solwin\Cpanel\Helper\Data');
$showproducts = $helper->getShowrelatedupsell();
if ($showproducts) {
    ?>
    <?php if ($exist): ?>
        <?php if ($type == 'related' || $type == 'upsell'): ?>
                <?php if ($type == 'related'): ?>
                <div style="float: left;width:100%;" class="rel-1 block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
                <?php else: ?>
                    <div class="rel-2 block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
                <?php endif; ?>
                <?php else: ?>
                    <div class="rel-3 block <?php /* @escapeNotVerified */ echo $class; ?>">
                    <?php endif; ?>
                    <div class="rightRelatedProductsTitle">
                        <div><?php /* @escapeNotVerified */ echo $title; ?></h2></div>
                    </div>
                    <div style="float: left;width:100%;" class="rel-4 block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class ?>-heading">
                      <?php /*?>  <?php if ($type == 'related' && $canItemsAddToCart): ?>
                            <div class="block-actions">
                                <?php  @escapeNotVerified  echo __('Check items to add to the cart or') ?>
                                <button type="button" class="action select" role="select-all"><span><?php  @escapeNotVerified echo __('select all') ?></span></button>
                            </div>
                        <?php endif; ?><?php */?>
                        <div class="owl-carousel-related ">
                            <ul>
                                <?php $iterator = 1; ?>
                                <?php foreach ($items as $_item): ?>
                                    <?php $available = ''; ?>
                                    <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                        <?php if (!$_item->getRequiredOptions()): ?>
                                            <?php $available = 'related-available'; ?>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <?php if ($type == 'related' || $type == 'upsell'): ?>
                                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item" style="display: none;">' : '</li><li class="item product product-item" style="display: none;">' ?>
                                    <?php else: ?>
                                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                                    <?php endif; ?>
                                    <div class="product-item-detial <?php /* @escapeNotVerified */ echo $available; ?>">
                                    <div class="itembox">
                                        <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                          <?php /*?>  <?php if (!$_item->getRequiredOptions()): ?>
                                                <div style="position: relative;" class="field choice related">
                                                    <input type="checkbox" class="checkbox related" id="related-checkbox<?php  echo $_item->getId() ?>" name="related_products[]" value="<?php  echo $_item->getId() ?>" />
                                                    <label class="label" for="related-checkbox<?php echo $_item->getId() ?>"><span><?php echo __('Add to Cart') ?></span></label>
                                                </div>
                                            <?php endif; ?><?php */?>
                                        <?php endif; ?>
                                        <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                                        <div class="product-img-block">
                                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                                                <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                               
                                            </a>
                                             </div>
                                             <div class="product details product-item-details">
                                            

                                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>

                                            <?php if ($templateType): ?>
                                                <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                            <?php endif; ?>

                                            <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                                <?php if (!$_item->getRequiredOptions()): ?>
                                                    <!--                                                    <div class="field choice related">
                                                                                                            <input type="checkbox" class="checkbox related" id="related-checkbox<?php // /* @escapeNotVerified */ echo $_item->getId()      ?>" name="related_products[]" value="<?php // /* @escapeNotVerified */ echo $_item->getId()      ?>" />
                                                                                                            <label class="label" for="related-checkbox<?php // /* @escapeNotVerified */ echo $_item->getId()      ?>"><span><?php // /* @escapeNotVerified */ echo __('Add to Cart')      ?></span></label>
                                                                                                        </div>-->
                                                <?php endif; ?>
                                            <?php endif; ?>
                                            
                                            <h4><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                                    <?php echo $block->escapeHtml($_item->getName()) ?></a>
                                            </h4>
                                        </div>

                                            <?php if ($showWishlist || $showCompare || $showCart): ?>
                                               
                                                    <?php if ($showCart): ?>
                                                        <div class="add-to-cart-button">
                                                            <?php if ($_item->isSaleable()): ?>
                                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                                    <button class="button" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                                    </button>
                                                                <?php else: ?>
                                                                    <?php
                                                                    $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                                    ?>
                                                                    <button class="button"
                                                                            data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                                    </button>
                                                                <?php endif; ?>
                                                            <?php else: ?>
                                                                <?php if ($_item->getIsSalable()): ?>
                                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                                <?php else: ?>
                                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                                <?php endif; ?>
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endif; ?>

                                                <?php /*?>    <?php if ($showWishlist || $showCompare): ?>
                                                        <div class="secondary-addto-links actions-secondary" data-role="add-to-links" style="padding: 0 10px;">
                                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                                <a href="#" data-post='<?php  echo $block->getAddToWishlistParams($_item); ?>'  class="action towishlist" data-action="add-to-wishlist" title="<?php  echo __('Add to Wish List') ?>">
                                                                    <span><?php  echo __('Add to Wish List') ?></span>
                                                                </a>
                                                            <?php endif; ?>
                                                            <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                                <?php
                                                                $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                                ?>
                                                                <a href="#" class="action tocompare"
                                                                   data-post='<?php  echo $compareHelper->getPostDataParams($_item); ?>'
                                                                   data-role="add-to-links"
                                                                   title="<?php  echo __('Add to Compare'); ?>">
                                                                    <span><?php echo __('Add to Compare') ?></span>
                                                                </a>
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endif; ?><?php */?>
                                               
                                            <?php endif; ?>
                                       
                                        </div>
                                    </div>
                                    <?php echo($iterator == count($items) + 1) ? '</li>' : '' ?>
                                <?php endforeach ?>
                            </ul>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
            <?php if ($type == 'crosssell') { ?>
                <script>
                    require(['jquery', 'cpowlcarousel'], function ($) {
                        $(document).ready(function () {
                            $(".pro-slider").owlCarousel({
                                items: 4,
                                itemsDesktop: [1080, 3],
                                itemsDesktopSmall: [860, 2],
                                itemsTablet: [768, 3],
                                itemsTabletSmall: [639, 2],
                                itemsMobile: [360, 2],
                                pagination: false,
                                navigationText: ["<div class='lft-btn'><i class='fa fa-angle-left'></i></div>", "<div class='rgt-btn'><i class='fa fa-angle-right'></div>"],
                                navigation: true,
                            });
                        });
                    });
                </script>
            <?php } else { ?>
                <script>
                    require(['jquery', 'cpowlcarousel'], function () {
                        jQuery(document).ready(function () {
                            jQuery(".pro-slider").owlCarousel({
                                items: 5,
                                itemsDesktop: [1080, 4],
                                itemsDesktopSmall: [860, 3],
                                itemsTablet: [768, 3],
                                itemsTabletSmall: [639, 2],
                                itemsMobile: [360, 2],
                                pagination: false,
                                navigationText: ["<div class='lft-btn'><i class='fa fa-angle-left'></i></div>", "<div class='rgt-btn'><i class='fa fa-angle-right'></div>"],
                                navigation: true,
                            });

                         
                           
                        });
                    });



                </script>
                
                    <script>
					
					require(['jquery','domReady!'], function ($) {

                            setTimeout(function() {
                            jQuery(".product-col-related  .owl-carousel-related ul").owlCarousel({
                                items: 1,
								itemsDesktop: [1199, 1],
								itemsDesktopSmall: [979, 1],
								itemsTablet: [768, 1],
								itemsMobile: [360, 1],
                                autoHeight:true,
                                pagination: false,
                                navigationText: ["<div class='lft-btn'><i class='fa fa-angle-left'></i></div>", "<div class='rgt-btn'><i class='fa fa-angle-right'></div>"],
                                navigation: true,
                            });
							
                            },2000)
                        


                        });
					
					
					
                   




						require(['jquery', 'cpowlcarousel'], function () {
									jQuery(document).ready(function () {
									  
										jQuery(".upsell  .owl-carousel-related ul").owlCarousel({
											items: 4,
											
											pagination: false,
											navigationText: ["<div class='lft-btn'><i class='fa fa-angle-left'></i></div>", "<div class='rgt-btn'><i class='fa fa-angle-right'></div>"],
											navigation: true,
										});
										
                        });
                    });



                </script>
                
                
            <?php } ?>
        <?php } ?>
