<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
<?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;

    ?>

<div class="block new-main-product"> 
<?php if ($title): ?>

  <h3 role="heading" aria-level="2">
    <?php /* @escapeNotVerified */ echo $title; ?>
  </h3>
 
<?php endif ?>
<div class="block widget block-products-list <?php /* @escapeNotVerified */ echo $mode; ?>">
<div class="block-content">
  <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
  <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
    <div  class="products-row row <?php /* @escapeNotVerified */ echo $type; ?>">
      <?php $iterator = 1; ?>
      <?php foreach ($items as $_item): ?>
      <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<div class="col-xs-12 col-sm-3">' : '</div><div class="col-xs-12 col-sm-3">' ?>
     
        <div class="itembox">
          <div class="img-box">
            <div class="item-pro-attrabute">
            <?php 
              if($_item->getData('on_sale') == 1)
                echo "<span class='item-pro-bestsellerlist item-lbl-onsale'>On Sale</span><br>"; 
              if($_item->getData('is_bestseller') == 1)
                echo "<span class='item-pro-bestsellerlist'>Best Seller</span><br>"; 
              if($_item->getData('new_product') == 1 && $_item->getData('is_bestseller') == 0)
                echo "<span class='item-pro-bestsellerlist item-lbl-new'>New</span>"; // mutually exclusive bestseller/new
            ?>
            
              
              </div>
            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo"> <?php echo $block->getImage($_item, $image)->toHtml(); ?> </a>
            <?php if ($showWishlist || $showCompare || $showCart): ?>
            <?php if ($showWishlist || $showCompare): ?>
            <div class="actions-secondary" data-role="add-to-links"> 
              <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
              <a href="#" data-post='<?php echo $block->getAddToWishlistParams($_item); ?>' class="action towishlist" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>"> <i class="fa fa-heart" aria-hidden="true"></i> </a>
              <?php endif; ?>
              <?php /*?><?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                        <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                        <a href="#" class="action tocompare"
                                                           data-post='<?php  echo $compareHelper->getPostDataParams($_item); ?>'
                                                           title="<?php  echo __('Add to Compare') ?>">
                                                            <span><?php  echo __('Add to Compare') ?></span>
                                                        </a>
                                                    <?php endif; ?><?php */?>
              <a href="<?php  echo $block->getProductUrl($_item) ?>" class="product-item-photo"> <i class="fa fa-search-plus" aria-hidden="true"></i> </a> </div>
            <?php endif; ?>
            <?php endif; ?>

            
            <?php 
              if($_item->getData('customer_rated') == 1)
                echo "<div class='item-attrib-rating'><span class='item-lbl-custrated'>Customer Rated</span></div>"; 
            ?>
          </div>
          <?php
                                    echo $block->getProductPriceHtml($_item, $type);
                                    ?>
          <h4 > <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                           href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" > <span class="short-name"> <?php echo $block->escapeHtml($_item->getName()) ?></span> </a> </h4>
          <?php if ($templateType): ?>
          <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
          <?php endif; ?>
          <?php if ($showCart): ?>
          <div class="add-to-cart-button">
            <?php if ($_item->isSaleable()): ?>
            <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
            <button class="button" data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>"> 
            <i class="fa fa-plus" aria-hidden="true"></i> <span>
            <?php /* @escapeNotVerified */ echo __('Add to Cart') ?>
            </span> </button>
            <?php else: ?>
 <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper'); $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                            ?>
            <button class="button"  data-post='<?php /* @escapeNotVerified */ echo $postData; ?>' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>"> 
            <i class="fa fa-plus" aria-hidden="true"></i> <span>
            <?php /* @escapeNotVerified */ echo __('Add to Cart') ?>
            </span> </button>
            <?php endif; ?>
            <?php else: ?>
            <?php if ($_item->getIsSalable()): ?>
            <div class="stock available"><span>
              <?php /* @escapeNotVerified */ echo __('In stock') ?>
              </span></div>
            <?php else: ?>
            <div class="stock unavailable"><span>
              <?php /* @escapeNotVerified */ echo __('Out of stock') ?>
              </span></div>
            <?php endif; ?>
            <?php endif; ?>
          </div>
          <?php endif; ?>
        </div>
      
      <?php echo($iterator == count($items) + 1) ? '</div>' : '' ?>
      <?php endforeach ?>
      <div> </div>
      <?php echo $block->getPagerHtml() ?> </div>
  </div>
</div>
<?php endif; ?>
</div>
</div>
