<?php
/**
 * @var $this \Scommerce\GoogleTagManagerPro\Block\Checkout\Onepage
 */

$helper = $this->getHelper();

if (!$helper->isEnhancedEcommerceEnabled()) return;
$cartItems = $this->getCartItems();
?>
<script>
    //<![CDATA[
    require(['jquery', 'Magento_Checkout/js/model/quote', 'domReady'],function (jQuery,quote, domReady) {
		var old_shipping =''; var old_payment='';
        domReady(function () {
			//Fixed to make it compatible with latest jquery version. .live function is depricated
			jQuery(document).on('click','input:radio, button, submit', function(e){
				//shipping
				if (quote.shippingMethod()!=null){
					var shipping = quote.shippingMethod().carrier_code;
					if(shipping!=undefined && old_shipping!=shipping){
						old_shipping = shipping;
						steps(shipping, 1);
					}
				}
				//payment
				if (quote.paymentMethod()!=null){
					var payment = quote.paymentMethod().method;					
					if(payment!=undefined && old_payment!=payment){
						old_payment = payment;
						steps(payment, 2);
					}
				}
				//console.log('payment - '+ payment);
            });

            function steps(value, pos){
                if (value!=undefined){
                    //console.log(value,pos);
                    <?php $intCtr=0;?>
					dataLayer.push({
                            'event': 'checkout',
                            'ecommerce': {
                                'checkout': {
                                    'actionField': {'step': pos, 'option': value},
                                    'products': [
                                        <?php foreach($cartItems as $_quoteItem) : ?>
                                        <?php $intCtr++;?>
                                        <?php if ($_quoteItem->getParentItemId()) continue; ?>
                                        {
                                            'name': '<?php echo $this->escapeJsQuote($_quoteItem->getName()) ?>',
                                            'id': '<?php echo $this->escapeJsQuote($_quoteItem->getSku()) ?>',
                                            'price': '<?php echo $_quoteItem->getBasePrice() ?>',
                                            'brand': '<?php echo $this->escapeJsQuote($helper->getBrand($_quoteItem->getProduct())) ?>',
                                            'category': '<?php echo $this->escapeJsQuote($helper->getQuoteCategoryName($_quoteItem)) ?>',
                                            'quantity': '<?php echo $_quoteItem->getQty() ?>'
                                            <?php if ($intCtr==count($cartItems)):?>
                                        }]
                                    <?php else:?>
                                },
                                <?php endif;?>
                                <?php endforeach; ?>
                                }
                            },
                            'eventCallback': function() {
                            //document.location = 'checkout.html';
                        }
                    });
                }
            }
        })
    });
    //]]>
</script>