<footer class="page-footer">
  <h1>FOOTER TEST</h1>

  <div class="container">
    <div class="row">

      <div class="col-sm-4">
        <img src="/media/svgs/envelope-open-text.svg" alt="email" />
        <p>Email</p>
      </div>

      <div class="col-sm-4">
        <img src="/media/svgs/phone-office.svg" alt="phone" />
        <p>Telephone</p>
      </div>

      <div class="col-sm-4">
        <img src="/media/svgs/clock.svg" alt="clock" />
        <p>Office Hours</p>
      </div>

    </div>
  </div>

</footer>