<div class="footer-links-section">
  <ul class="footer-category-links">
    <li><a href="/in-ground.html">In Ground</a></li>
    <li><a href="/floors.html">Floors</a></li>
    <li><a href="/walls.html">Walls</a></li>
    <li><a href="/interior.html">Interior</a></li>
    <li><a href="/exterior.html">Exterior</a></li>
    <li><a href="/roofing.html">Roofing</a></li>
  </ul>
  <ul class="footer-general-links">
    <li><a href="/shop.html">Shop By Product</a></li>
    <li><a href="/delivery-information">Information Hub</a></li>
    <li><a href="/about-us">About Us</a></li> 
    <li><a href="/contact-us">Contact Us</a></li>
    <li><a href="/news">Blog</a></li>
    <li><a href="/">Home</a></li>
  </ul>
</div>