<div class="footer-contact-section">
  <h1>FOOTER CONTACT</h1>

  <div class="container">
    <div class="row">

      <div class="col-sm-4">
        <div class="footer-contact-box">
          <div class="footer-contact-image">
            <img src="/media/svgs/envelope-open-text.svg" alt="email" />
          </div>
          <div class="footer-contact-text">
            <h5>Email</h5>
            <p>info@ecomerchant.co.uk</p>
          </div>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="footer-contact-box">
          <div class="footer-contact-image">
            <img src="/media/svgs/phone-office.svg" alt="phone" />
          </div>
          <div class="footer-contact-text">
            <h5>Telephone</h5>
            <p>Sales and Technical</p>
            <p>Enquiries: +44 (0)1793 847 444</p>
          </div>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="footer-contact-box">
          <div class="footer-contact-image">
            <img src="/media/svgs/clock.svg" alt="clock" />
          </div>
          <div class="footer-contact-text">
            <h5>Office Hours</h5>
            <p>8am - 5pm</p>
            <p>Monday to Friday</p>
          </div>
        </div>
      </div>

    </div>
  </div>

</div>